project:
  type: website
  output-dir: docs

website:
  title: "claralclaroll.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Preview of Dataset
      - about.qmd

format:
  html:
    theme: unity
    css: styles.css
    toc: true

editor: visual

