---
title: "Preview of Dataset"
---

``` {r, eval=TRUE,echo=TRUE}
library(tidyverse)
library(dplyr)
target<- c("['Robert Schumann', 'Vladimir Horowitz']","['Franz Joseph Haydn', 'Pro Arte Quartet']","['Felix Mendelssohn', 'Vladimir Horowitz']", "['Frédéric Chopin', 'Vladimir Horowitz']", "['Franz Liszt', 'Vladimir Horowitz']","['Sergei Rachmaninoff', 'Vladimir Horowitz']", "['Ludwig van Beethoven', 'Staatskapelle Berlin', 'Richard Strauss']")
spotifydata<-read.csv("spotify-data.csv")
newdata<- spotifydata %>%
  select(name,artists, year,danceability, energy, popularity,valence)%>%
  filter(artists%in%target)%>%
  filter(popularity>=1)
head(newdata)
```

Overview of Dataset 

The dataset I am using is filtered from an original, larger dataset that included 1 Million song tracks between 2000 and 2023. This original dataset was retrieved from Spotify platform using the Python library "Spotipy". This allows users to access music data provided via APIs. The larger dataset collected also includes 19 features, a total of 61,445 unique artists and 82 genres in the data.

Features/Variables of Dataset 

1. Popularity refers to the popularity of the track by the public. The popularity rating ranges from 0 to 100.
2.Year refers to the release year of the track. 
3.Energy refers to the level of intensity and activity of the piece (from 0 to 1)
4. Danceability refers to the level of liveliness of the piece (from 0 to 1)
5. Valence refers to the level of music positivity. This means that pieces with higher valence are usually more upbeat and happy, while pieces with lower valence are usually sadder and slower. 
6. Name refers to the name of the piece
7. Artists refers to the artist of the piece


```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://claralclaroll.shinyapps.io/claralgithubapp/ "> </iframe>
```
